### ISSUE TITLE
isso script included on pages that don't support comments

### ISSUE THREAD

**Issue by budui** [mtn/cocoa-eh-hugo-theme#88] opened 2018-03-23 15:14 UTC
Hi, (3th...). I find this in my [blog](https://jinxiapu.com)
![image](https://user-images.githubusercontent.com/16448529/37836830-80cf0cce-2eee-11e8-859f-6dc34706fc67.png)
I think maybe isso comment should be loaded in [post page](https://github.com/mtn/cocoa-eh-hugo-theme/blob/master/layouts/blog/single.html)
![image](https://user-images.githubusercontent.com/16448529/37836879-a915e720-2eee-11e8-9fad-883965bb67be.png)

**Comment by mtn** [comment] 2018-03-23 15:34
Hm, I'm going to have to take a closer look at this later, because I'm not sure how isso was configured. Is your config file somewhere that I can take a look?

Also, tagging @vsund because I remember you originally implemented this and might be able to help better/faster than I can.

**Comment by budui** [comment] 2018-03-23 16:46
You can visit [client configuration](https://posativ.org/isso/docs/configuration/client/) for more information.
I just use config file like [server configuration](https://posativ.org/isso/docs/configuration/server/). In fact, I think that maybe it's independent of server configuration.
I can do more tests for this or make a pull request  tomorrow. (The current time is 0:46 in China...)

**Comment by budui** [comment] 2018-03-23 16:51
Maybe unrelated, Your response is so fast. Thank you! I feel the charm of GITHUB, as a new programmer. and Thank you for your tolerance of my poor English.

**Comment by vsund** [comment] 2018-03-23 16:56
You should have a `<div class="isso" id="isso-thread"></div>` somewhere in your HTML. That's the point where the Isso script inserts the comments.

I think the error message appears when Isso can't find this `div`. Might be that you're misspelled the `#isso-thread` id or removed this tag?

Edit: For reference, it should be automatically in your HTML: https://github.com/mtn/cocoa-eh-hugo-theme/blob/dev/layouts/blog/single.html#L75

**Comment by mtn** [comment] 2018-03-23 18:59
From looking at the [actual blog](https://jinxiapu.com/):

1. The message only seems to be logged on pages where the Isso script was embedded but there weren't comments, like on the main page. Actually, I it's worth including the embed script only in the templates for "blog" pages, where comments will show up, to avoid sourcing extra stuff from some CDN. (unless the script gets cached, but flushed when it's not needed -- I can check what happens, but this isn't high priority at all)

2. The #isso-thread id is present, as expected, on the pages it should be.

I might be misunderstanding, but I'm not seeing any unexpected behavior. So please clarify when you can, @Jinxiapu.

**Comment by budui** [comment] 2018-03-24 00:05
Well...,I think the Isso script should be only loaded in page with comments. (the page with `<div class="isso" id="isso-thread"></div>`). I mean these [lines](https://github.com/mtn/cocoa-eh-hugo-theme/blob/dev/layouts/partials/footer_scripts.html#L24) should be move into single.html.

**Comment by mtn** [comment] 2018-03-24 00:16
Got it. Yea, as I was saying above, I agree with that. If you want to make the PR, go for it. If not, I can make the change.

Thanks for bringing this up!

**Comment by mtn** [comment] 2018-03-24 00:17
This is also definitely a sensible thing to do because aside from the loading overhead, the script clearly isn't intended to run on pages that aren't configured for comments.

**Comment by mtn** [comment] 2018-03-25 15:37
@Jinxiapu are you planning on implementing this?

**Comment by mtn** [comment] 2018-03-27 16:33
Resolved by #90, thanks @Jinxiapu!

**Closed as completed by mtn** 2018-03-27 16:33 UTC
